# Generated by Django 3.0.7 on 2022-02-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod_testing', '0002_auto_20220228_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonsevodasset',
            name='test_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fonsevodasset',
            name='test_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
